# Social
title:              WB3 K8s | Spring Cloud Scalable Starter
description:        "Opinionated microservices reference architecture using Kubernetes, Spring Cloud, and HashiCorp technology."
twitter:            wb3tech
authors:            "Bill Bensing"

theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-include-cache
